version: 2
defaults:
  taggedReleasesFilter: &taggedReleasesFilter
    tags:
      only: /^\d+\.\d+\.\d+((a|b|rc)\d)?$/ # matches 1.2.3, 1.2.3a1, 1.2.3b1, 1.2.3rc1 etc..
jobs:
  build:
    docker:
      - image: circleci/python:2.7.16-stretch
    steps:
      - checkout
      - run: pip install --user .
      - run: sudo pip install coverage pylint==1.9.3 pycodestyle
      - run: make test
      - persist_to_workspace:
          root: .
          paths:
            - .coverage
      - store_artifacts:
          path: pylint.out
      - store_artifacts:
          path: pycodestyle.out

  coverage:
    docker:
      - image: circleci/python:2.7.16-stretch
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: sudo pip install coverage
      - run: coverage report --show-missing | tee /tmp/coverage
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /tmp/coverage
          destination: test-coverage

  snyk:
    docker:
      - image: circleci/python:2.7.16-stretch
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: python setup.py egg_info
      - run: cp analytics_python.egg-info/requires.txt requirements.txt
      - run: pip install --user -r requirements.txt
      - run: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh

  test_27:
    docker:
      - image: circleci/python:2.7.16-stretch
    steps:
      - checkout
      - run: pip install --user .
      - run: make e2e_test

  test_35: &test_35
    docker:
      - image: circleci/python:3.5.7-stretch
    steps:
      - checkout
      - run: pip install --user .
      - run: sudo pip install coverage pylint==1.9.3 pycodestyle
      - run: make test
      - run: make e2e_test

  test_36:
    <<: *test_35
    docker:
      - image: circleci/python:3.6.9-stretch

  test_37:
    <<: *test_35
    docker:
      - image: circleci/python:3.7.4-stretch

  test_38:
    <<: *test_35
    docker:
      - image: circleci/python:3.8-buster

  publish:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - run: sudo pip install twine
      - run: make release

workflows:
  version: 2
  build_test_release:
    jobs:
      - build:
          filters:
            <<: *taggedReleasesFilter
      - test_27:
          filters:
            <<: *taggedReleasesFilter
      - test_35:
          filters:
            <<: *taggedReleasesFilter
      - test_36:
          filters:
            <<: *taggedReleasesFilter
      - test_37:
          filters:
            <<: *taggedReleasesFilter
      - test_38:
          filters:
            <<: *taggedReleasesFilter
      - publish:
          requires:
            - build
            - test_27
            - test_35
            - test_36
            - test_37
            - test_38
          filters:
            <<: *taggedReleasesFilter
            branches:
              ignore: /.*/
  static_analysis:
    jobs:
      - build
      - coverage:
          requires:
            - build
      - snyk:
          context: snyk
          requires:
            - build
  scheduled_e2e_test:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
                - scheduled_e2e_testing
    jobs:
      - test_27
      - test_35
      - test_36
      - test_37
      - test_37
